### ISSUE TITLE
Compile 

### ISSUE THREAD

**Issue by falc0n0** [Waf1leCodes/SandyTetris#1]
Hello, I would like to compile the game, but they encounter many difficulties, especially after compiling with cmake, do you use any more libraries than raylib?
I have already successfully compiled JollyTetris and I love it.

**Comment by JacobC09** [comment]
I super happy your enjoying my games :D This is probably because I didn't include the "external" folder in the git repo and cmake is trying to add a sub directory that doesn't exist.

**Comment by JacobC09** [comment]
should be fixed now :D just redownload the repo

**Comment by falc0n0** [comment]
Thanks man it worked it was very cool congratulations

**Comment by JacobC09** [comment]
:D
